baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections_dir: slides

collections:
  examples:
    output: True
    permalink: /slides/:path
  work:
    output: True
    permalink: /slides/:path
